version: 2
jobs:
<<<<<<< HEAD
  step-two:
=======
  step-three:
>>>>>>> b41b51cc8b7eba209733079b34e1ee541e75bec4
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
            export PATH=$HOME/.yarn/bin:$PATH
      - run: yarn install --offline --frozen-lockfile
      - run:
          name: Run ci checks
          command: yarn ci-check
      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2
  main:
    jobs:
<<<<<<< HEAD
      - step-two
=======
      - step-three
>>>>>>> b41b51cc8b7eba209733079b34e1ee541e75bec4
